name: CI - Build LibreOffice

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Please select branch to work on'
        required: false
        default: 'build'

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /workspace
    steps:
      - name: Verify repository exists
        run: |
          if [ ! -d ".git" ]; then
            echo "Repository not found in /workspace. Please mount your local repository folder."
            exit 1
          fi

      - name: Set target branch variable
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            echo "Using manual input branch: ${{ github.event.inputs.branch }}"
            echo "TARGET_BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          else
            branch="${GITHUB_REF#refs/heads/}"
            echo "Using push branch: $branch"
            echo "TARGET_BRANCH=$branch" >> $GITHUB_ENV
          fi

      - name: Checkout
        run: |
          git fetch origin $TARGET_BRANCH
          git reset --hard
          git checkout origin/$TARGET_BRANCH

      - name: Prepare build configuration
        run: |
          echo -e "--enable-dbgutil\n--enable-compiler-plugins\n--enable-kf5\n--disable-compiler-plugins-analyzer-pch\n--disable-dependency-tracking\n--disable-split-debug\n--enable-odk\n--disable-dconf\n--enable-python=internal\n--enable-atspi-tests" > autogen.input
          ./autogen.sh

      - name: Run make
        run: make -O  build unitcheck slowcheck
